version = 0.1

[default.deploy.parameters]
stack_name = "jira-translator"
resolve_s3 = true
s3_prefix = "jira-translator"
capabilities = "CAPABILITY_IAM"
image_repositories = []
[default.global.parameters]
region = "ap-northeast-2"
profile = "AdministratorAccess-700388609892"
